services:
  postgres:
    image: postgres:16
    container_name: phoenix_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: phoenix_db
    ports:
      - "5432:5432"
    volumes:
      - phoenix_postgres_data:/var/lib/postgresql/data

volumes:
  phoenix_postgres_data: